
###  getAll Users con POST
GET http://localhost:4500/v1/users

### Crear un User Resgitrandose con POST
POST http://localhost:4500/v1/users/signUp/
Content-Type: application/json

{
  "username": "Jorgiño444432",
  "email": "wills322@example.com",
  "password": "123456S#",
  "registeredAt": "2024-02-05T12:00:00Z"
}

### Crear un User Resgitrandose con POST
POST http://localhost:4500/v1/videos
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmU3ZDc4MWZjNmI4YjY4YjRjODhmNSIsImlhdCI6MTcxMTE3NzM3OSwiZXhwIjoxNzExMjYzNzc5fQ.CxDP0M8_YAX_JFW7Kg5Wr3XqxvLfJA9YZcT5kWZgFOQ

{
  "name": "Nike Air Max",
  "description": "The Nike Air Max sneakers provide cushioning and support for all-day comfort.",
  "price": 129.99,
  "special_price": 99.99
}

### Iniciar Sesion
POST http://localhost:4500/v1/users/signIn/
Content-Type: application/json

{
  "username": "Jorgiño444432",
  "email": "wills322@example.com",
  "password": "123456S#"
}

###
# Obtener un usuario por su ID
###
GET http://localhost:4500/v1/users/65c096976a9f1af4795034a2

### Eliminar usuario por ID
DELETE http://localhost:4500/v1/users/65c315d483d1c949e8403688

### Actualizar usuario por ID
PATCH http://localhost:4500/v1/users/:id
Content-Type: application/json

{
  "username": "nuevo_nombre_de_usuario",
  "email": "nuevo_email@example.com",
  "password": "NuevaPassword123!",
  "registeredAt": "2024-02-05T12:00:00Z",
  "role": "admin"
}


### obtener Videos Privados solo si estas registrado
GET http://localhost:4500/v1/videos/privates
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzA5Njk3NmE5ZjFhZjQ3OTUwMzRhMiIsImlhdCI6MTcwNzEyMDI4MCwiZXhwIjoxNzA3MjA2NjgwfQ.euxtZaG1Ivxc0YBpuNjH01WuFX6LoegRIlvpM8UkuZo

### obtener Videos Publicos
GET http://localhost:4500/v1/videos/publics


###
# Obtener todos los videos
###

GET http://localhost:4500/v1/videos
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzA5Njk3NmE5ZjFhZjQ3OTUwMzRhMiIsImlhdCI6MTcwNzEyMDI4MCwiZXhwIjoxNzA3MjA2NjgwfQ.euxtZaG1Ivxc0YBpuNjH01WuFX6LoegRIlvpM8UkuZo



###
# Crear un nuevo video Recomendable Hacerlo desde Postman o otro con FormDAta
###
POST http://localhost:4500/v1/videos
Content-Type: multipart/form-data
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzA5Njk3NmE5ZjFhZjQ3OTUwMzRhMiIsImlhdCI6MTcwNzEyMDI4MCwiZXhwIjoxNzA3MjA2NjgwfQ.euxtZaG1Ivxc0YBpuNjH01WuFX6LoegRIlvpM8UkuZo

{
  "title": "Título del video",
  "description": "Descripción del video",
  "credits": "Créditos del video",
  "publicationDate": "2023-09-15T14:30:00Z",
  "isPublic": "true",
  "uploader": "ID_del_usuario_que_subió_el_video",
  "year": "2023",
  "director": "Director del video",
  "duration": "120",
  "rate": "8",
  "poster": "https://example.com/video-poster.jpg",
  "genre": "Adventure",
  "url": "https://example.com/video-url",
  "videoFile":"link imane"
}

###
# Obtener un video por su ID
###

GET http://localhost:4500/v1/videos/:id


###
# Eliminar un video por su ID
###

DELETE http://localhost:4500/v1/videos/:id
x-access-token: token

###
# Actualizar un video por su ID
###

PATCH http://localhost:4500/v1/videos/:id
Content-Type: application/json
x-access-token: token

{
  "title": "Nuevo título del video",
  "description": "Nueva descripción del video",
  "credits": "Nuevos créditos del video",
  "publicationDate": "2023-09-15T14:30:00Z",
  "isPublic": "true",
  "year": "2023",
  "director": "Nuevo director del video",
  "duration": "150",
  "rate": "9",
  "poster": "https://example.com/new-video-poster.jpg",
  "genre": "Action",
  "url": "https://example.com/new-video-url"
}
