
###  getAll Users con POST
GET https://node-js-challenge-xi.vercel.app/v1/users

### Crear un User Resgitrandose con POST
POST https://node-js-challenge-xi.vercel.app/v1/users/signUp/
Content-Type: application/json

{
  "username": "AliciaTerry",
  "email": "alicia.terry@example.com",
  "password": "Alicia4567!",
  "registeredAt": "2024-04-02T18:20:00Z"
}


### Iniciar Sesion
POST https://node-js-challenge-xi.vercel.app/v1/users/signIn/
Content-Type: application/json

{
  "username": "Jorgiño444432",
  "email": "wills322@example.com",
  "password": "123456S#"
}

###
# Obtener un usuario por su ID
###
GET https://node-js-challenge-xi.vercel.app/v1/users/65fe7d781fc6b8b68b4c88f5

### Eliminar usuario por ID
DELETE https://node-js-challenge-xi.vercel.app/v1/users/65ffbf1a52a84c9618515d90
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmU3ZDc4MWZjNmI4YjY4YjRjODhmNSIsImlhdCI6MTcxMTI1ODk0MCwiZXhwIjoxNzExMzQ1MzQwfQ.o5dUaEIfXNMIyY-tmG4k-lCfRDzZizfjMoC_UglUfWI

### Actualizar usuario por ID
PATCH https://node-js-challenge-xi.vercel.app/v1/users/:id
Content-Type: application/json

{
  "username": "nuevo_nombre_de_usuario",
  "email": "nuevo_email@example.com",
  "password": "NuevaPassword123!",
  "registeredAt": "2024-02-05T12:00:00Z"
}




### Crear un Prodcuto 
POST https://node-js-challenge-xi.vercel.app/v1/products
Content-Type: application/json

{
  "name": "Nike Air Max",
  "description": "The Nike Air Max sneakers provide cushioning and support for all-day comfort.",
  "stock": 100,
  "price": 129.99,
  "brand_special_price": [
    {
      "userId": "65ff47525b747f326a8a8667",
      "special_price": 99.99
    },
    {
      "userId": "65ff4454fa182ea253363ed3",
      "special_price": 89.99
    }
  ]
}

### obtener Productos en stock 
GET https://node-js-challenge-xi.vercel.app/v1/products/

### obtener Precios por usuarios y nombre de prodcuto
GET https://node-js-challenge-xi.vercel.app/v1/products/price/65ff4439fa182ea253363ed1/Nike%20Air%20Max


###
# Obtener todos los productos
###

GET https://node-js-challenge-xi.vercel.app/v1/products/all

###
# Obtener un producto por su ID
###

GET https://node-js-challenge-xi.vercel.app/v1/products/65ff08293c3a8c5789f8f48c


###
# Eliminar un producto por su ID
###

DELETE https://node-js-challenge-xi.vercel.app/v1/products/:id
x-access-token: token

###
# Actualizar un producto por su ID
###

PATCH https://node-js-challenge-xi.vercel.app/v1/products/65ff2c2040f404c23195ad90
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmY0NzUyNWI3NDdmMzI2YThhODY2NyIsImlhdCI6MTcxMTIyODc1NCwiZXhwIjoxNzExMzE1MTU0fQ.zVM6iRv_sh8mXSnk_wak9t2s4kXthj8Usx_Csz646E0

{
  "name": "Nike Air Max",
  "description": "The Nike Air Max sneakers provide cushioning and support for all-day comfort.",
  "stock": 100,
  "price": 129.99,
  "brand_special_price": [
    {
      "userId": "65ff47525b747f326a8a8667",
      "special_price": 99.99
    },
    {
      "userId": "65ff4454fa182ea253363ed3",
      "special_price": 89.99
    }
  ]
}
